export const fmpConstants = {
  GAINERS_REQUEST: "GAINERS_REQUEST",
  GAINERS_REQUEST_SUCCESS: "GAINERS_REQUEST_SUCCESS",
  GAINERS_REQUEST_FAILURE: "GAINERS_REQUEST_FAILURE",

  LOSERS_REQUEST: "LOSERS_REQUEST",
  LOSERS_REQUEST_SUCCESS: "LOSERS_REQUEST_SUCCESS",
  LOSERS_REQUEST_FAILURE: "LOSERS_REQUEST_FAILURE",

  ACTIVE_REQUEST: "ACTIVE_REQUEST",
  ACTIVE_REQUEST_SUCCESS: "ACTIVE_REQUEST_SUCCESS",
  ACTIVE_REQUEST_FAILURE: "ACTIVE_REQUEST_FAILURE",
};
