export const portfoliosConstants = {
  PORTFOLIOS_REQUEST: "PORTFOLIOS_REQUEST",
  PORTFOLIOS_REQUEST_SUCCESS: "PORTFOLIOS_REQUEST_SUCCESS",
  PORTFOLIOS_REQUEST_FAILURE: "PORTFOLIOS_REQUEST_FAILURE",
};
